baseURL = "https://miguelablp.github.io/galeria/"
languageCode = "pt-br"
title = "Meu Portfólio"
theme = "gallery"


[params]
  [params.socialIcons]
    instagram = "https://www.instagram.com/miguelablp"
    linkedin = "https://www.linkedin.com/in/miguel-d-758a283a9/?locale=en"
